# Site settings
title: Alexis Aktor website
email: aktor.alexis@gmail.com
description:  # this means to ignore newlines until "baseurl:"
  Amazing work from A.K
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: noTwitter
github_username:  biosy

# Build settings
markdown: kramdown
